# Generated by Django 4.2.30 on 2026-05-16 07:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrm', '0001_initial'),
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('is_billable', models.BooleanField(default=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('timer', 'Timer'), ('desktop', 'Desktop App'), ('mobile', 'Mobile App')], default='manual', max_length=50)),
                ('is_running', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='hrm.employee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_logs', to='pm.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_logs', to='pm.task')),
            ],
            options={
                'db_table': 'time_logs',
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='screenshots/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='screenshots/thumbs/%Y/%m/%d/')),
                ('captured_at', models.DateTimeField()),
                ('activity_level', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_blurred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='hrm.employee')),
                ('time_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='tracking.timelog')),
            ],
            options={
                'db_table': 'screenshots',
            },
        ),
        migrations.CreateModel(
            name='ProductivityMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('tasks_completed', models.IntegerField(default=0)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('efficiency_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('focus_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('collaboration_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_metrics', to='hrm.employee')),
            ],
            options={
                'db_table': 'productivity_metrics',
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_active_seconds', models.IntegerField(default=0)),
                ('total_idle_seconds', models.IntegerField(default=0)),
                ('mouse_clicks', models.IntegerField(default=0)),
                ('keyboard_strokes', models.IntegerField(default=0)),
                ('activity_level', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('productivity_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('apps_used', models.JSONField(blank=True, default=list)),
                ('websites_visited', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='hrm.employee')),
            ],
            options={
                'db_table': 'activity_logs',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
