# Generated by Django 4.2.30 on 2026-05-17 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLogApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_time_logs', to=settings.AUTH_USER_MODEL)),
                ('time_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='tracking.timelog')),
            ],
            options={
                'db_table': 'time_log_approvals',
            },
        ),
        migrations.CreateModel(
            name='AppUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=255)),
                ('app_identifier', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('is_productive', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_usages', to='tracking.activitylog')),
            ],
            options={
                'db_table': 'app_usages',
            },
        ),
    ]
