# Generated by Django 4.2.30 on 2026-05-16 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'X / Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit')], max_length=50)),
                ('account_name', models.CharField(max_length=255)),
                ('account_handle', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('follower_count', models.IntegerField(default=0)),
                ('profile_url', models.URLField(blank=True)),
                ('profile_image', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='core.organization')),
            ],
            options={
                'db_table': 'social_accounts',
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('media_urls', models.JSONField(blank=True, default=list)),
                ('platforms', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('engagement_stats', models.JSONField(blank=True, default=dict)),
                ('ai_generated', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='core.organization')),
            ],
            options={
                'db_table': 'social_posts',
            },
        ),
        migrations.CreateModel(
            name='SocialMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_message_id', models.CharField(blank=True, max_length=255)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_handle', models.CharField(blank=True, max_length=255)),
                ('sender_avatar', models.URLField(blank=True)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('dm', 'Direct Message'), ('mention', 'Mention'), ('comment', 'Comment'), ('review', 'Review'), ('email', 'Email')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_messages', to='core.organization')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.socialaccount')),
            ],
            options={
                'db_table': 'social_messages',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('objective', models.CharField(choices=[('awareness', 'Brand Awareness'), ('engagement', 'Engagement'), ('traffic', 'Traffic'), ('leads', 'Lead Generation'), ('sales', 'Sales')], max_length=50)),
                ('platforms', models.JSONField(default=list)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=50)),
                ('performance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.organization')),
                ('posts', models.ManyToManyField(blank=True, related_name='campaigns', to='social.socialpost')),
            ],
            options={
                'db_table': 'campaigns',
            },
        ),
    ]
