# Generated by Django 4.2.30 on 2026-05-17 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('new_message', 'New Message'), ('new_comment', 'New Comment'), ('new_mention', 'New Mention'), ('post_published', 'Post Published'), ('post_failed', 'Post Failed'), ('follow', 'New Follower')], max_length=50)),
                ('target_url', models.URLField(blank=True)),
                ('secret', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('failed', 'Failed')], default='active', max_length=20)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('fail_count', models.IntegerField(default=0)),
                ('payload_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='core.organization')),
                ('social_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='social.socialaccount')),
            ],
            options={
                'db_table': 'webhooks',
            },
        ),
        migrations.CreateModel(
            name='PostQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('processing', 'Processing'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('platform_post_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='social.socialpost')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.socialaccount')),
            ],
            options={
                'db_table': 'post_queue',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='social_media/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='social_media/thumbs/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('gif', 'GIF'), ('document', 'Document')], max_length=20)),
                ('size_bytes', models.IntegerField(default=0)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='core.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_files',
            },
        ),
        migrations.CreateModel(
            name='PostAnalytic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_post_id', models.CharField(blank=True, max_length=255)),
                ('impressions', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('video_views', models.IntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='social.socialpost')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.socialaccount')),
            ],
            options={
                'db_table': 'post_analytics',
                'unique_together': {('post', 'social_account')},
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=50)),
                ('usage_count', models.IntegerField(default=0)),
                ('avg_reach', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_trending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='core.organization')),
            ],
            options={
                'db_table': 'hashtags',
                'unique_together': {('organization', 'tag', 'platform')},
            },
        ),
    ]
